core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/TaskTimedSuite.scala

Introduce BIO#timed

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/internal/TaskToReactivePublisher.scala
core/shared/src/test/scala/monix/bio/TaskMiscSuite.scala

Introduce BIO.toReactivePublisher

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/TaskErrorSuite.scala

Add `onErrorRestart`

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/internal/TaskConversions.scala
core/shared/src/main/scala/monix/bio/internal/TaskToReactivePublisher.scala
core/shared/src/test/scala/monix/bio/TaskConversionsSuite.scala
core/shared/src/test/scala/monix/bio/TaskErrorSuite.scala

Introduce BIO.toAsync

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/TaskMiscSuite.scala

This resolves https://github.com/monix/monix-bio/issues/39
Probably some more tests are needed?

Implement BIO.tapError

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/TaskWanderSuite.scala

Closes #22 
I commented one test since BIO.memoize is not implemented yet - so I think we should wait with merging this PR.

Issue #22 - BIO.wander

---

core/shared/src/main/scala/monix/bio/UIO.scala

Add missing methods to UIO companion object

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/internal/BiCallback.scala
core/shared/src/main/scala/monix/bio/internal/TaskMemoize.scala
core/shared/src/test/scala/monix/bio/TaskMemoizeOnSuccessSuite.scala
core/shared/src/test/scala/monix/bio/TaskMemoizeSuite.scala

Implement .memoize and .memoizeOnSuccess

---

core/shared/src/test/scala/monix/bio/TaskRaceSuite.scala

Re-enabling disabled task timeout test since `memoize` is implemented now.

Add memoized task timeout test

---

core/shared/src/main/scala/monix/bio/TaskLocal.scala
core/shared/src/test/scala/monix/bio/SimpleBIOTestSuite.scala
core/shared/src/test/scala/monix/bio/TaskAsyncBoundarySuite.scala
core/shared/src/test/scala/monix/bio/TaskCancellationSuite.scala
core/shared/src/test/scala/monix/bio/TaskDoOnCancelSuite.scala
core/shared/src/test/scala/monix/bio/TaskExecuteOnSuite.scala
core/shared/src/test/scala/monix/bio/TaskExecuteWithModelSuite.scala
core/shared/src/test/scala/monix/bio/TaskExecuteWithOptionsSuite.scala
core/shared/src/test/scala/monix/bio/TaskLocalSuite.scala
core/shared/src/test/scala/monix/bio/TaskStartSuite.scala

Implement TaskLocal

---

core/shared/src/main/scala/monix/bio/Fiber.scala
core/shared/src/main/scala/monix/bio/internal/TaskCancellation.scala
core/shared/src/main/scala/monix/bio/internal/TaskConnection.scala
core/shared/src/main/scala/monix/bio/internal/TaskConnectionComposite.scala
core/shared/src/main/scala/monix/bio/internal/TaskConnectionRef.scala
core/shared/src/main/scala/monix/bio/internal/TaskGather.scala
core/shared/src/main/scala/monix/bio/internal/TaskGatherN.scala
core/shared/src/main/scala/monix/bio/internal/TaskGatherUnordered.scala
core/shared/src/main/scala/monix/bio/internal/UnsafeCancelUtils.scala
core/shared/src/test/scala/monix/bio/TaskCancellationSuite.scala
core/shared/src/test/scala/monix/bio/TaskConnectionCompositeSuite.scala
core/shared/src/test/scala/monix/bio/TaskConnectionSuite.scala

Return UIO in Fiber#cancel

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/TaskErrorSuite.scala

Add onErrorRestartLoop

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/Task.scala
core/shared/src/main/scala/monix/bio/UIO.scala
core/shared/src/test/scala/monix/bio/BIOMapNSuite.scala

Added mapN functions for BIO.

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/BIODoOnFinishSuite.scala

Added doOnFinish method to BIO.

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/TaskMiscSuite.scala

Added restartUntil method to BIO.

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/Task.scala
core/shared/src/main/scala/monix/bio/UIO.scala
core/shared/src/test/scala/monix/bio/TaskErrorSuite.scala

Implement rethrow

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/internal/BIOStartAndForget.scala
core/shared/src/test/scala/monix/bio/BIOStartAndForgetSuite.scala

Added startAndForget method to BIO.

---

.travis.yml
build.sbt
core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/BiCallback.scala
core/shared/src/main/scala/monix/bio/Fiber.scala
core/shared/src/main/scala/monix/bio/Task.scala
core/shared/src/main/scala/monix/bio/TaskLike.scala
core/shared/src/main/scala/monix/bio/TaskLocal.scala
core/shared/src/main/scala/monix/bio/UIO.scala
core/shared/src/main/scala/monix/bio/instances/CatsConcurrentEfectForTask.scala
core/shared/src/main/scala/monix/bio/internal/TaskRunLoop.scala
core/shared/src/test/scala/monix/bio/TaskConversionsKSuite.scala
core/shared/src/test/scala/monix/bio/TaskExecuteWithOptionsSuite.scala
core/shared/src/test/scala/monix/bio/TaskMiscSuite.scala
rootdoc.txt

I suppose it fixes #81 but it will be ongoing work for a long time

Setup doctest and update part of the scaladocs

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/Task.scala
core/shared/src/test/scala/monix/bio/TaskEvalAlwaysSuite.scala
core/shared/src/test/scala/monix/bio/TaskEvalAsyncSuite.scala
core/shared/src/test/scala/monix/bio/TaskEvalOnceSuite.scala
core/shared/src/test/scala/monix/bio/TaskMaterializeSuite.scala
core/shared/src/test/scala/monix/bio/TaskMemoizeOnSuccessSuite.scala
core/shared/src/test/scala/monix/bio/TaskMemoizeSuite.scala

BIO.evalOnce

---

core/jvm/src/test/scala/monix/bio/TaskCallbackSafetyJVMSuite.scala
core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/BiCallback.scala
core/shared/src/main/scala/monix/bio/Task.scala
core/shared/src/main/scala/monix/bio/instances/CatsConcurrentForTask.scala
core/shared/src/main/scala/monix/bio/internal/BIOStartAndForget.scala
core/shared/src/main/scala/monix/bio/internal/TaskCancellation.scala
core/shared/src/main/scala/monix/bio/internal/TaskConversions.scala
core/shared/src/main/scala/monix/bio/internal/TaskCreate.scala
core/shared/src/main/scala/monix/bio/internal/TaskFromFuture.scala
core/shared/src/main/scala/monix/bio/internal/TaskGather.scala
core/shared/src/main/scala/monix/bio/internal/TaskGatherUnordered.scala
core/shared/src/main/scala/monix/bio/internal/TaskStart.scala
core/shared/src/test/scala/monix/bio/BaseLawsSuite.scala
core/shared/src/test/scala/monix/bio/TaskCallbackSafetySuite.scala
core/shared/src/test/scala/monix/bio/TaskCallbackSuite.scala
core/shared/src/test/scala/monix/bio/TaskFlatMapSuite.scala
core/shared/src/test/scala/monix/bio/TaskMemoizeOnSuccessSuite.scala
core/shared/src/test/scala/monix/bio/TaskMemoizeSuite.scala

Make BiCallback extend (Either[Cause[E], A] => Unit)

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/internal/ForwardCancelable.scala
core/shared/src/main/scala/monix/bio/internal/TaskBracket.scala
core/shared/src/main/scala/monix/bio/internal/TaskConnection.scala
core/shared/src/main/scala/monix/bio/internal/TaskGather.scala
core/shared/src/main/scala/monix/bio/internal/TaskMapBoth.scala
core/shared/src/main/scala/monix/bio/internal/TaskRace.scala
core/shared/src/main/scala/monix/bio/internal/TaskRacePair.scala
core/shared/src/test/scala/monix/bio/TaskBracketSuite.scala

Port of https://github.com/monix/monix/pull/1120

Improve backpressure on finalizers

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/Task.scala
core/shared/src/main/scala/monix/bio/UIO.scala
core/shared/src/main/scala/monix/bio/internal/TaskRaceList.scala
core/shared/src/test/scala/monix/bio/TaskRaceSuite.scala

Introduce `BIO.raceMany`

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/main/scala/monix/bio/BIOLocal.scala
core/shared/src/main/scala/monix/bio/Task.scala
core/shared/src/main/scala/monix/bio/UIO.scala
core/shared/src/test/scala/monix/bio/TaskAsyncBoundarySuite.scala
core/shared/src/test/scala/monix/bio/TaskCancellationSuite.scala
core/shared/src/test/scala/monix/bio/TaskDeferActionSuite.scala
core/shared/src/test/scala/monix/bio/TaskDoOnCancelSuite.scala
core/shared/src/test/scala/monix/bio/TaskExecuteOnSuite.scala
core/shared/src/test/scala/monix/bio/TaskExecuteWithModelSuite.scala
core/shared/src/test/scala/monix/bio/TaskExecuteWithOptionsSuite.scala
core/shared/src/test/scala/monix/bio/TaskLocalSuite.scala
core/shared/src/test/scala/monix/bio/TaskStartSuite.scala
core/shared/src/test/scala/monix/bio/TaskWanderUnorderedSuite.scala

Implement BIO.wanderUnordered

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/TaskFlatMapSuite.scala

#8 
@Avasil ready for review :-)

Implement flatMapLoop from Monix Task

---

docs/src/mdoc/overview/gettingstarted.md

This is the first version of the getting started page. I was inspired by both monix and akka documentation, I really like when in docs I have complete code that can be run. I'm open for any suggestions on the form, contents, etc :)

Getting started documentation

---

core/shared/src/main/scala/monix/bio/BIO.scala
core/shared/src/test/scala/monix/bio/TaskFlipSuite.scala

#41 
@Avasil I think my examples will need some looking at, I really couldn't think of anything better at the time, perhaps we can come up with some better ones?

Implement flip and flipWith

---

core/shared/src/main/scala/monix/bio/internal/TaskBracket.scala
core/shared/src/test/scala/monix/bio/TaskBracketSuite.scala

Fixes #111 Port of https://github.com/monix/monix/pull/1175

Non-terminating cancel if acquire fails

---

.travis.yml
core/shared/src/main/scala/monix/bio/BIO.scala
docs/src/mdoc/overview/errorhandling.md
docs/src/mdoc/overview/index.md

First (hopefully of many) part of #113 
Any feedback is greatly appreciated, I'm learning to write docs as I go so all comments will be useful, whether it's about grammar, style of writing, poorly constructed sentences, confused wording, bad explanation, better examples suggestions etc.

Documentation: Error Handling section

---

core/shared/src/main/scala/monix/bio/IO.scala

Implements https://github.com/monix/monix-bio/issues/174

Add IO.flatTap

---

core/shared/src/main/scala/monix/bio/IO.scala

Ported *> and <*

---

.github/workflows/build.yml
.github/workflows/release.yml
build.sbt

Just wanted to corroborate that it was not something todo just with _monix-connect_
Have opened an [issue on sbt-ci-release](https://github.com/olafurpg/sbt-ci-release/).

Fix pipeline 

---

core/jvm/src/main/scala/monix/bio/internal/TaskRunSyncUnsafe.scala
core/jvm/src/test/scala/monix/bio/TaskBlockingSuite.scala

[Bugfix] ClassCastException when IO is in Termination state with runSyncUnsafe execution

---

README.md
website/pages/en/index.js

This is how it will look like:

Add discord badge
